### ISSUE TITLE
404: File Not Found

### ISSUE THREAD

**Issue by enderphan94** [kadena-community/getting-started#7]
My http://localhost:8080/explorer/development is up running but still got this error while running

```
npm run start -- fund --keys "68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9" --predicate "keys-all"
```

```
> getting-started@1.0.0 start
> ts-node -T src/index.ts fund --keys 68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9 --predicate keys-all

Funding account:  k:68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9
Public Key: 68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9
An error occurred while calling send API: Error: <h1>404: File Not Found!</h1>
    at parseResponse (/Users/enderphan/getting-started/node_modules/@kadena/chainweb-node-client/src/parseResponse.ts:19:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async send (/Users/enderphan/getting-started/node_modules/@kadena/chainweb-node-client/src/send.ts:26:12)
    at async Object.submit (/Users/enderphan/getting-started/node_modules/@kadena/client/src/client/client.ts:284:31)
    at async Command.<anonymous> (/Users/enderphan/getting-started/src/index.ts:25:7)
Error: <h1>404: File Not Found!</h1>
    at parseResponse (/Users/enderphan/getting-started/node_modules/@kadena/chainweb-node-client/src/parseResponse.ts:19:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async send (/Users/enderphan/getting-started/node_modules/@kadena/chainweb-node-client/src/send.ts:26:12)
    at async Object.submit (/Users/enderphan/getting-started/node_modules/@kadena/client/src/client/client.ts:284:31)
    at async Command.<anonymous> (/Users/enderphan/getting-started/src/index.ts:25:7)
```

**Comment by alber70g** [comment]
Thank you for reporting. We'll look into it 👀

**Comment by alber70g** [comment]
We've changed the network name across all development tooling from `fast-development` to `development`. We've pushed a fix in #8. 

If you cannot use the latest version, you can pass the environment variable `CHAINWEB_NETWORK="development"` to set the correct network.

The full command becomes

```sh
CHAINWEB_NETWORK="development" npm run start -- fund --keys "<public-key>" --predicate "keys-all"
```

**Comment by enderphan94** [comment]
> We've changed the network name across all development tooling from `fast-development` to `development`. We've pushed a fix in #8.
> 
> If you cannot use the latest version, you can pass the environment variable `CHAINWEB_NETWORK="development"` to set the correct network.
> 
> The full command becomes
> 
> ```shell
> CHAINWEB_NETWORK="development" npm run start -- fund --keys "<public-key>" --predicate "keys-all"
> ```

Please update this here as well https://docs.kadena.io/build/quickstart

**Comment by enderphan94** [comment]
Got the same error with another command, even though I've tried to add "CHAINWEB_NETWORK="development"' but no luck.

```
npm run start -- deploy --keys "68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9" --predicate "keys-all" --sign-manually


> getting-started@1.0.0 start
> ts-node -T src/index.ts deploy --keys 68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9 --predicate keys-all --sign-manually

Deploying with account: k:68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9
Public Key: 68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9
(node:15586) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
1. To sign this transaction, open https://chainweaver.kadena.network
2. Open the "SigBuilder" tab
3. Copy and Paste the following transaction into the "Signature Builder" field

{"cmd":"{\"payload\":{\"exec\":{\"code\":\"(namespace 'free)\\n(module hello-world G\\n  (defcap G () true)\\n  (defun say-hello(name:string)\\n    (format \\\"Hello, {}! ~ from: 68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9\\\" [name])\\n  )\\n)\",\"data\":{}}},\"meta\":{\"gasLimit\":100000,\"gasPrice\":1e-8,\"sender\":\"k:68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9\",\"ttl\":28800,\"creationTime\":1716973132,\"chainId\":\"0\"},\"networkId\":\"development\",\"signers\":[{\"pubKey\":\"68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9\",\"scheme\":\"ED25519\"}],\"nonce\":\"kjs:nonce:1716973132995\"}","hash":"V0iCuggtr61Gkx3KgfjWlPEkdVJ8i-vQnd2-qg1Y7kQ","sigs":[{"pubKey":"68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9"}]}

4. Make sure the "Hash" is "V0iCuggtr61Gkx3KgfjWlPEkdVJ8i-vQnd2-qg1Y7kQ". This ensures that you're singing the same transaction
5. In the "Details" tab, verify that your public key is in the "Signers" section
and you're not signing for something malicious
6. Click "Sign"
7. the whole JSON and paste it here (or just value of the "sig" key-value pair)
? Please enter the Chainweaver result, or just the signature {"cmd":"{\"payload\":{\"exec\":{\"code\":\"(namespace 'free)\\n(module hello-world G\\n  (defcap G () true)\\n  (defun say-hello(name:string)\\n    
(format \\\"Hello, {}! ~ from: 68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9\\\" [name])\\n  
)\\n)\",\"data\":{}}},\"meta\":{\"gasLimit\":100000,\"gasPrice\":1e-8,\"sender\":\"k:68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9\",\"ttl\":28800,\"creationTime\":1716972991,\"chainId\":\"0\"},
\"networkId\":\"fast-development\",\"signers\":[{\"pubKey\":\"68ee6900a0e65ce1c445d611fceae282e4fa25943e3e645b7be7704c8b55a1c9\",\"scheme\":\"ED25519\"}],\"nonce\":\"kjs:nonce:1716972991800\"}","hash":"97xO9rtdkdb
9EesS1_u3VPwEVVOar8JyQjJJj5YA6P4","sigs":[{"sig":"95e952e8e0728e7500772d488a24ccd98bb0c855435ba9481195efae752663fdd0367fd51b683e31580e3b20253e45ab63fab546ed061f2568ee9a34e88ba502"}]}
An error occurred while calling send API: Error: <h1>404: File Not Found!</h1>
    at parseResponse (/Users/enderphan/getting-started/node_modules/@kadena/chainweb-node-client/src/parseResponse.ts:19:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async send (/Users/enderphan/getting-started/node_modules/@kadena/chainweb-node-client/src/send.ts:26:12)
    at async Object.submit (/Users/enderphan/getting-started/node_modules/@kadena/client/src/client/client.ts:284:31)
    at async Command.<anonymous> (/Users/enderphan/getting-started/src/index.ts:58:7)
Error: <h1>404: File Not Found!</h1>
    at parseResponse (/Users/enderphan/getting-started/node_modules/@kadena/chainweb-node-client/src/parseResponse.ts:19:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async send (/Users/enderphan/getting-started/node_modules/@kadena/chainweb-node-client/src/send.ts:26:12)
    at async Object.submit (/Users/enderphan/getting-started/node_modules/@kadena/client/src/client/client.ts:284:31)
    at async Command.<anonymous> (/Users/enderphan/getting-started/src/index.ts:58:7)
```

**Comment by ash-vd** [comment]
Did you pull the latest version, where we now default to `development` for the network? You can omit specifying the `CHAINWEB_NETWORK` environment variable, although that shouldn't be the issue here.

In your request I can still see `"networkId": "fast-development"` which is where you're issue lies. You can try adding `console.log(NETWORK_ID)` on [line 30](https://github.com/kadena-community/getting-started/blob/main/src/deploy.ts#L30) to see what the value is, it should be `development`.
